In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [7]:
b=np.arange(0,10,2)
print("Array b:",b)

Array b: [0 2 4 6 8]


In [10]:
d=np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
e=np.ones((3,2))
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
f=np.eye(4)
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manupulation Function

In [15]:
a1=np.array([1,2,3])
reshaped=np.reshape(a1,(1,3))
print("reshaped array:",reshaped)

reshaped array: [[1 2 3]]


In [22]:
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1)
print("flattened array",flattened)

flattened array [ 1  2  3  4  5  6  7  8  9 10]


In [30]:
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1)
print("transposed array:\n", transposed)

transposed array:
 [[1 3]
 [2 4]]


In [27]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [[1 2]
 [3 4]]


In [29]:
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2])
print("stacked array:\n",stacked)

stacked array:
 [1 2 3 4]


In [32]:
g=np.array([1,2,3,4])
added=np.add(g,2)
print("added 2 to g:",added)

added 2 to g: [3 4 5 6]


In [33]:
squared=np.power(g,2)
print("squared g:",squared)

squared g: [ 1  4  9 16]


In [34]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [36]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("dot product of and a1 and a:",dot_product) 

dot product of and a1 and a: 14


# Statistical Functions

In [38]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [42]:
var=np.var(s)
print("variable of s:", var)

variable of s: 1.25


In [39]:
std_dev=np.std(s)
print("standard deviation of s:", std_dev)

standard deviation of s: 1.118033988749895


In [40]:
minimum=np.min(s)
print("min of s:", minimum)

min of s: 1


In [41]:
maximum=np.max(s)
print("max of s:", maximum)

max of s: 4


# Random Sampling Functions

In [43]:
random_vals=np.random.rand(3)
print("random values:",random_vals)

random values: [0.6476263  0.64342069 0.95586659]


In [44]:
np.random.seed(0)
random_vals=np.random.rand(3)
print("random values:",random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [47]:
rand_int=np.random.randint(0,10,size=5)
print("random intergers:", rand_int)

random intergers: [8 1 6 7 7]
