In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

# Creating Arrays

In [3]:
my_list=[10,1,2,3,4,5]
my_list

[10, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr=np.array(my_list)
arr

array([10,  1,  2,  3,  4,  5])

In [6]:

type(arr)

numpy.ndarray

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros(5,dtype=int) #1d array

array([0, 0, 0, 0, 0])

In [12]:
np.zeros((2,2)) #2d array

array([[0., 0.],
       [0., 0.]])

In [13]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [14]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.random.rand(4)

array([0.16719118, 0.71305724, 0.94283467, 0.39318216])

In [18]:
np.random.rand(2,2)

array([[0.75392597, 0.17355781],
       [0.78662468, 0.90697525]])

In [19]:
np.random.randint(3)

2

In [20]:
np.random.randint(10,15)

11

In [21]:
np.random.randint(1,5,3)

array([4, 4, 1], dtype=int32)

In [22]:
np.random.randint(1,5,4)

array([4, 1, 4, 4], dtype=int32)

In [23]:
np.random.randint(-5,2,3)

array([-1, -3, -3], dtype=int32)

In [24]:
np.random.randint(10,40,(10,10))

array([[36, 31, 26, 35, 10, 35, 36, 23, 10, 12],
       [10, 16, 14, 35, 12, 30, 39, 25, 28, 16],
       [33, 16, 28, 34, 33, 37, 11, 15, 22, 34],
       [12, 18, 18, 16, 33, 22, 31, 28, 12, 16],
       [34, 16, 19, 16, 20, 30, 22, 39, 39, 29],
       [19, 12, 15, 22, 19, 38, 15, 35, 38, 33],
       [36, 16, 33, 29, 16, 10, 27, 14, 27, 34],
       [11, 24, 23, 33, 12, 25, 22, 17, 25, 13],
       [16, 18, 21, 10, 28, 23, 33, 17, 14, 13],
       [21, 10, 17, 22, 24, 39, 31, 31, 16, 14]], dtype=int32)

In [25]:
ri=np.random.randint(10,40,(10,10))
ri

array([[29, 36, 22, 33, 25, 21, 18, 27, 38, 30],
       [25, 28, 21, 36, 24, 16, 30, 11, 14, 39],
       [39, 35, 28, 26, 25, 13, 32, 34, 16, 35],
       [10, 12, 22, 33, 13, 33, 33, 27, 10, 26],
       [14, 13, 32, 13, 26, 28, 23, 28, 16, 21],
       [14, 19, 13, 15, 35, 27, 36, 23, 38, 31],
       [39, 18, 28, 10, 18, 24, 20, 34, 17, 21],
       [22, 30, 24, 17, 18, 24, 11, 35, 26, 35],
       [25, 38, 23, 38, 25, 14, 37, 24, 16, 29],
       [22, 38, 23, 11, 27, 22, 33, 25, 38, 18]], dtype=int32)

In [26]:
ri=np.random.randint(10,40,(3,5))
ri

array([[34, 38, 19, 17, 12],
       [14, 24, 17, 36, 15],
       [28, 30, 23, 24, 24]], dtype=int32)

In [27]:
len(ri)

3

In [28]:
ri.shape

(3, 5)

In [29]:
id(ri)

2389147687248

In [30]:
ri

array([[34, 38, 19, 17, 12],
       [14, 24, 17, 36, 15],
       [28, 30, 23, 24, 24]], dtype=int32)

# Slicing in numpy

In [31]:
ri[:]

array([[34, 38, 19, 17, 12],
       [14, 24, 17, 36, 15],
       [28, 30, 23, 24, 24]], dtype=int32)

In [32]:
ri[1]

array([14, 24, 17, 36, 15], dtype=int32)

In [33]:
ri[0:3]

array([[34, 38, 19, 17, 12],
       [14, 24, 17, 36, 15],
       [28, 30, 23, 24, 24]], dtype=int32)

In [34]:
ri_1=np.random.randint(10,40,(10,10))
ri_1

array([[36, 27, 35, 11, 21, 26, 12, 35, 26, 19],
       [33, 30, 35, 32, 18, 14, 35, 28, 26, 32],
       [12, 22, 33, 37, 25, 33, 33, 26, 16, 27],
       [31, 15, 11, 10, 35, 26, 37, 15, 39, 13],
       [29, 23, 34, 28, 28, 24, 32, 31, 13, 10],
       [10, 31, 15, 17, 13, 38, 37, 38, 20, 29],
       [21, 35, 31, 22, 36, 19, 38, 33, 23, 32],
       [21, 25, 31, 13, 20, 26, 10, 35, 12, 20],
       [11, 35, 14, 24, 15, 36, 24, 31, 35, 29],
       [15, 19, 35, 31, 14, 13, 32, 35, 29, 37]], dtype=int32)

In [35]:
ri_1=np.random.randint(10,40,(10,10))
print(ri_1)

[[25 39 16 30 34 20 22 27 13 31]
 [25 20 14 23 22 29 30 35 33 19]
 [26 12 35 25 26 17 28 38 24 33]
 [24 18 31 34 14 23 22 30 23 39]
 [32 27 27 26 16 21 22 17 22 27]
 [35 15 12 32 24 12 27 33 16 31]
 [22 15 23 30 10 28 19 39 36 26]
 [11 23 37 12 16 20 38 34 16 22]
 [38 29 37 21 37 17 14 39 14 38]
 [22 15 38 19 12 24 16 23 39 12]]


In [36]:
ri_1

array([[25, 39, 16, 30, 34, 20, 22, 27, 13, 31],
       [25, 20, 14, 23, 22, 29, 30, 35, 33, 19],
       [26, 12, 35, 25, 26, 17, 28, 38, 24, 33],
       [24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27],
       [35, 15, 12, 32, 24, 12, 27, 33, 16, 31],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [11, 23, 37, 12, 16, 20, 38, 34, 16, 22],
       [38, 29, 37, 21, 37, 17, 14, 39, 14, 38],
       [22, 15, 38, 19, 12, 24, 16, 23, 39, 12]], dtype=int32)

In [37]:
ri_1[:]

array([[25, 39, 16, 30, 34, 20, 22, 27, 13, 31],
       [25, 20, 14, 23, 22, 29, 30, 35, 33, 19],
       [26, 12, 35, 25, 26, 17, 28, 38, 24, 33],
       [24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27],
       [35, 15, 12, 32, 24, 12, 27, 33, 16, 31],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [11, 23, 37, 12, 16, 20, 38, 34, 16, 22],
       [38, 29, 37, 21, 37, 17, 14, 39, 14, 38],
       [22, 15, 38, 19, 12, 24, 16, 23, 39, 12]], dtype=int32)

In [38]:
ri_1[3:8]

array([[24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27],
       [35, 15, 12, 32, 24, 12, 27, 33, 16, 31],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [11, 23, 37, 12, 16, 20, 38, 34, 16, 22]], dtype=int32)

In [39]:
 print(ri_1[3,8])

23


In [40]:
ri_1

array([[25, 39, 16, 30, 34, 20, 22, 27, 13, 31],
       [25, 20, 14, 23, 22, 29, 30, 35, 33, 19],
       [26, 12, 35, 25, 26, 17, 28, 38, 24, 33],
       [24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27],
       [35, 15, 12, 32, 24, 12, 27, 33, 16, 31],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [11, 23, 37, 12, 16, 20, 38, 34, 16, 22],
       [38, 29, 37, 21, 37, 17, 14, 39, 14, 38],
       [22, 15, 38, 19, 12, 24, 16, 23, 39, 12]], dtype=int32)

In [41]:
ri_1[-5]

array([35, 15, 12, 32, 24, 12, 27, 33, 16, 31], dtype=int32)

In [42]:
 ri_1[-5,-3]

np.int32(33)

In [43]:
ri_1

array([[25, 39, 16, 30, 34, 20, 22, 27, 13, 31],
       [25, 20, 14, 23, 22, 29, 30, 35, 33, 19],
       [26, 12, 35, 25, 26, 17, 28, 38, 24, 33],
       [24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27],
       [35, 15, 12, 32, 24, 12, 27, 33, 16, 31],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [11, 23, 37, 12, 16, 20, 38, 34, 16, 22],
       [38, 29, 37, 21, 37, 17, 14, 39, 14, 38],
       [22, 15, 38, 19, 12, 24, 16, 23, 39, 12]], dtype=int32)

In [44]:
ri_1[::3]

array([[25, 39, 16, 30, 34, 20, 22, 27, 13, 31],
       [24, 18, 31, 34, 14, 23, 22, 30, 23, 39],
       [22, 15, 23, 30, 10, 28, 19, 39, 36, 26],
       [22, 15, 38, 19, 12, 24, 16, 23, 39, 12]], dtype=int32)

In [45]:
ri_1[::-5]

array([[22, 15, 38, 19, 12, 24, 16, 23, 39, 12],
       [32, 27, 27, 26, 16, 21, 22, 17, 22, 27]], dtype=int32)

In [46]:
ri_1[2]

array([26, 12, 35, 25, 26, 17, 28, 38, 24, 33], dtype=int32)

In [47]:
(ri_1[2])
(ri_1[:,-2])

array([13, 33, 24, 23, 22, 16, 36, 16, 14, 39], dtype=int32)

In [48]:
ri_1[:,-8]

array([16, 14, 35, 31, 27, 12, 23, 37, 37, 38], dtype=int32)

In [49]:
ri_1[2:6,3:5]

array([[25, 26],
       [34, 14],
       [26, 16],
       [32, 24]], dtype=int32)

In [50]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

# numpy masking or filter

In [53]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [54]:
id(mat)

2389183873648

In [55]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [57]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [58]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [59]:
mat[mat==50]

array([50])

In [60]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
range(5)

range(0, 5)

In [62]:
r=range(5)
r

range(0, 5)

In [63]:
for i in r:
    print(i)

0
1
2
3
4


In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [65]:
list(range(1,10,3))


[1, 4, 7]

In [66]:
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [67]:
np.random.rand(5)

array([0.15978804, 0.99713106, 0.38515652, 0.09638514, 0.03656796])

# Operations

In [68]:
a=np.random.randint(10,20,10)
a


array([15, 18, 10, 10, 19, 11, 17, 19, 15, 11], dtype=int32)

In [69]:
id(a)

2389183877200

# python program to generat otp

In [70]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4404


In [71]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [72]:
def wish():
    print('good even')
wish()

wish()

wish()

good even
good even
good even


In [73]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000022C4673CB00>


In [1]:
x=[1,2,3]
y=x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
